# Generated by Django 4.0.4 on 2022-05-01 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_project_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_date', models.DateField(auto_now_add=True)),
                ('submitted_time', models.TimeField(auto_now_add=True)),
                ('submitted_on_time', models.BooleanField(default=True)),
                ('marks_alloted', models.IntegerField(default=0)),
                ('submission_file', models.FileField(upload_to='documents')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
