# Generated by Django 4.0.4 on 2022-05-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
